/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import app.controller.ManajemenUser;
import app.model.md_login;
import javax.swing.JOptionPane;

/**
 *
 * @author ran
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private ManajemenUser usr;
    private home_admin adm = new home_admin();
    private home_dosen dsn = new home_dosen();
    private home_mahasiswa mhs = new home_mahasiswa();
    private md_login login;
    
    public login() {
        initComponents();
        usr = new ManajemenUser(this);
    }
    
    public String getUsername(){
        return txtusername.getText();
    }
    
    public String getPassword(){
        return String.valueOf(txtpassword.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/login1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, 140, 50));

        txtusername.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtusername.setForeground(new java.awt.Color(95, 44, 130));
        txtusername.setBorder(null);
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 210, 40));

        txtpassword.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(95, 44, 130));
        txtpassword.setBorder(null);
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, 210, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/login.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       usr.cekLogin();
            if(usr.getStatus()=="adm"){
                JOptionPane.showMessageDialog(rootPane, "Berhasil login sebagai admin");
                adm.setVisible(true);
                this.dispose();
            } else if (usr.getStatus()=="dsn"){
                JOptionPane.showMessageDialog(rootPane, "Berhasil login sebagai dosen");
                dsn.setVisible(true);
                this.dispose();
            } else if (usr.getStatus()=="mhs"){
                 JOptionPane.showMessageDialog(rootPane, "Berhasil login sebagai mahasiswa");
                mhs.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Password/Username salah");
            }
 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
